# Generated by Django 3.2.16 on 2022-12-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
